### ISSUE TITLE
gui_alignment issue

### ISSUE THREAD

**Issue by claireboulange** [csmsoftware/IMPaCTS#2]
Hi Gordon, 

I hope you are well. 

I have been trying to use the gui_alignment script from the Imoact toolbox. I got the following error message : 

# figure = csm_gui_alignment( spectra,'model_rspa')
Error using load
Unable to read file 'iconsnew'. No such file or directory.

Error in setupdefaults (line 45)
load iconsnew;

Error in uiAlignment (line 30)
metadata = setupdefaults(metadata);     % set default parameters

Error in csm_gui_alignment/callBaseTool (line 99)
			obj.linkprop = uiAlignment( obj.input.spectra.x_scale,
            obj.input.spectra.X, obj.input.aligned_X );

Error in csm_gui_alignment (line 52)
			obj = callBaseTool( obj );

As indicated in the IMPact toolbox document, 'model_rspa' was generated using the automatic alignment (RSPA model as generated by csm_rspa).

I also get the same error when using only the spectra 
  figure = csm_gui_alignment( spectra);

Please let me know what should I do, is it an input problem ? 

Thank you 

Best wishes, 

Claire

**Comment by gordondavies** [comment]
Hi Claire,

I think I've identified the cause, but before I do another release with the updated code, could you test if the following fixes your problem?

Please download, unzip, and copy the enclosed file to a location available to your Matlab path, for example inside the toolbox folder itself, and try and run your code again.

[iconsnew.mat.zip](https://github.com/csmsoftware/IMPaCTS/files/1638966/iconsnew.mat.zip)

If this works, I will push a new release with this missing file.

Best wishes,

Gordon

**Comment by claireboulange** [comment]
Hi Gordon, 

It is working now. Thank you very much !

Best, 

Claire

**Comment by damidseq** [comment]
Hi Gordon,

I run into the same issue. Thanks for the fix. 

best regards,
